### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by YoshiGamerFR** [YoshiGamerFR/image-analyzer#1]
- [x] If not found, create an "output" folder
- [ ] Allow the user to choose their background color
- [ ] Ask the user if they want to change the background color
- [ ] Allow the user to choose the color they want to background to be changed into

**Comment by YoshiGamerFR** [comment]
If you have any suggestion you can either create an Issue (preferred option) or comment below this one.
